### ISSUE TITLE
Creating CRDs appears to be broken.

### ISSUE THREAD

**Issue by nimakaviani** [cnoe-io/cnoe-cli#14]
When using the HEAD build for the CNOE cli to generate CRDs, the generated template does not properly populate the backstage template.

The error appears to be due to placing `dependencies` directly under `parameters` as below:

```
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  description: Deploy Resource to Kubernetes
  name: deploy-resources
  title: Deploy Resources
spec:
  owner: guest
  parameters:
    - dependencies:
        resources:
          oneOf:
            - $yaml: resources/acm.services.k8s.aws.certificate.yaml
            - $yaml: resources/apigatewayv2.services.k8s.aws.api.yaml
            - $yaml: resources/apigatewayv2.services.k8s.aws.authorizer.yaml
            - $yaml: resources/apigatewayv2.services.k8s.aws.deployment.yaml
            - $yaml: resources/apigatewayv2.services.k8s.aws.integration.yaml
            - $yaml: resources/apigatewayv2.services.k8s.aws.route.yaml
            - $yaml: resources/apigatewayv2.services.k8s.aws.stage.yaml
            - $yaml: resources/apigatewayv2.services.k8s.aws.vpclink.yaml
```
whereas it should in fact be `parameters.properties.dependencies`

working on a fix here: https://github.com/cnoe-io/cnoe-cli/tree/fix-bad-crd-error

This has to do with defaulting the value for `insertAt` which makes things complicated.
