### ISSUE TITLE
add more prerequisite configurations to CNOE CLI

### ISSUE THREAD

**Issue by nimakaviani** [cnoe-io/cnoe-cli#3]
We have sample prerequisites that cover verifications for ACK S3 and Spark Operators, see below.

```yaml
apiVersion: cnoe.io/v1alpha1
kind: Prerequisite
metadata:
  name: spark
spec:
  pods:
  - name: spark-operator
  crds:
  - group: sparkoperator.k8s.io
    kind: SparkApplications
    version: v1beta2
  - group: sparkoperator.k8s.io
    kind: ScheduledSparkApplications
    version: v1beta2
```

We need more exhaustive list of prerequisites based on incoming requirements.
